"""initial schema

Revision ID: 31d2ad486257
Revises: 
Create Date: 2026-04-19 21:31:47.042318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31d2ad486257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'created_at')
    # ### end Alembic commands ###
